import React, { useState } from 'react';
import './Renderers.css';
import MarkdownRenderer from '../../Shared/MarkdownRenderer';

interface EssayRendererProps {
    content: string; // The prompt and thesis
}

const EssayRenderer: React.FC<EssayRendererProps> = ({ content }) => {
    const [showThesis, setShowThesis] = useState(false);

    // Naive parsing based on the prompt structure in brain_service (Prompt Statement / Thesis Hint)
    // Since we output raw text now, we look for keywords if they exist, or just show raw
    // The prompt format usually has "Prompt Statement:" and "Thesis Hint:" labels if generated by the old model logic, 
    // but the NEW strict logic just returns text. 
    // We might need to guess the split or just render markdown.

    // Let's try to detect if it's split by double newline
    const sections = content.split('\n\n');

    // Heuristic: Shortest section might be the title/thesis, Longest is the prompt content.

    return (
        <div className="essay-renderer-container">
            <div className="essay-paper glass-card">
                <div className="paper-header">
                    <span className="paper-icon">✍️</span>
                    <h3>UPSC Mains Evaluator</h3>
                    <span className="paper-marks">250 Marks</span>
                </div>

                <div className="paper-content">
                    <div className="prompt-section">
                        <h4>Essay Topic</h4>
                        <div className="prompt-text">
                            <MarkdownRenderer content={content} />
                        </div>
                    </div>

                    <div className="thesis-hint-section">
                        <button
                            className="reveal-btn"
                            onClick={() => setShowThesis(!showThesis)}
                        >
                            {showThesis ? '🙈 Hide Thesis Hint' : '💡 Reveal Thesis Hint'}
                        </button>

                        {showThesis && (
                            <div className="thesis-content glass-panel">
                                <p>
                                    <em>Analysis:</em> Look for key keywords in the prompt above.
                                    (Note: Full thesis decomposition is available in the 'Socratic' mode).
                                </p>
                            </div>
                        )}
                    </div>
                </div>

                <div className="paper-footer">
                    <span>Time Allowed: 3 Hours</span>
                    <button className="start-writing-btn">Start Writing Timer</button>
                </div>
            </div>
        </div>
    );
};

export default EssayRenderer;
