
const escapeHtml = (unsafe: string | number | null | undefined): string => {
    if (unsafe === null || unsafe === undefined) return '';
    return String(unsafe)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
};

// Define a minimal interface for the question object to avoid 'any'
interface QuestionData {
    question_text: string;
    year: string | number;
    option_a: string;
    option_b: string;
    option_c: string;
    option_d: string;
    correct_option: string;
}

export const generateCombatSheet = (questions: QuestionData[], title: string = 'Combat Sheet') => {
    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
        alert('Please allow popups to generate the Combat Sheet.');
        return;
    }

    const styles = `
        <style>
            body { font-family: 'Georgia', serif; line-height: 1.5; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
            h1 { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; }
            .meta { text-align: center; color: #666; font-style: italic; margin-bottom: 30px; }
            .question-item { margin-bottom: 25px; page-break-inside: avoid; }
            .q-text { font-weight: bold; margin-bottom: 10px; }
            .options { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-left: 20px; }
            .option { font-size: 0.95em; }
            .answer-key { margin-top: 50px; page-break-before: always; }
            .key-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(80px, 1fr)); gap: 10px; border-top: 1px solid #ccc; padding-top: 20px; }
            .key-item { font-size: 0.9em; }
            @media print {
                body { font-size: 11pt; }
                .no-print { display: none; }
            }
        </style>
    `;

    const safeTitle = escapeHtml(title);

    const questionsHtml = questions.map((q, idx) => `
        <div class="question-item">
            <div class="q-text">${idx + 1}. ${escapeHtml(q.question_text)} <span style="font-size:0.8em;color:#777">(${escapeHtml(q.year)})</span></div>
            <div class="options">
                <div class="option">A) ${escapeHtml(q.option_a)}</div>
                <div class="option">B) ${escapeHtml(q.option_b)}</div>
                <div class="option">C) ${escapeHtml(q.option_c)}</div>
                <div class="option">D) ${escapeHtml(q.option_d)}</div>
            </div>
        </div>
    `).join('');

    const answerKeyHtml = questions.map((q, idx) => `
        <div class="key-item"><strong>${idx + 1}.</strong> ${escapeHtml(q.correct_option)}</div>
    `).join('');

    const content = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>${safeTitle}</title>
            ${styles}
        </head>
        <body>
            <h1>${safeTitle}</h1>
            <div class="meta">Generated by UPSC War Room • ${questions.length} Questions</div>

            <div class="questions">
                ${questionsHtml}
            </div>

            <div class="answer-key">
                <h2>Answer Key & Explanations</h2>
                <div class="key-grid">
                    ${answerKeyHtml}
                </div>
            </div>

            <script>
                window.onload = () => { window.print(); }
            </script>
        </body>
        </html>
    `;

    printWindow.document.write(content);
    printWindow.document.close();
};
